# Path to your oh-my-zsh installation.
export DOTFILES=$HOME/dotfiles
export ZSH=$DOTFILES/Zshell/ohmyzsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="alanpeabody"
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.


# =============== plugins =============== 

plugins=(git python pip vi-mode history-substring-search zsh-autosuggestions zsh-syntax-highlighting autojump sudo colored-man-pages command-not-found common-aliases gitignore themes)

# Expand plugins

expand=(docker nvm docker-compose code nmap)

for item in ${expand[@]}; do
    if ( command -v $item > /dev/null 2>&1 ); then
        plugins=(${plugins[@]} $item)
    fi
done

# if ( command -v code.exe > /dev/null 2>&1 ) || ( command -v code > /dev/null 2>&1 ); then
#     plugins=(vscode ${plugins[@]})
# fi



# tmux
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOQUIT=false
plugins=(tmux $plugins)



# ========================================================

# User configuration

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
#export PATH=$PATH:/usr/java/jre1.8.0_131/bin
#export PATH=$PATH:/usr/java/jdk1.8.0_131/bin

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

export EDITOR='vim'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"

# Zsh configuration
setopt correct

source $ZSH/oh-my-zsh.sh


# =====================

# 設定中文 防亂碼
export LANGUAGE="zh_TW.UTF-8"
export LANG="zh_TW.UTF-8"
export LC_ALL="zh_TW.UTF-8"

export EDITOR='vim' #設定預設編輯器
setopt correct #會告訴你命令是否錯誤
setopt auto_pushd #cd記憶

#======= 標準補完設定 ======
autoload -Uz compinit && compinit -i
#=========================

setopt list_packed #補完顯示
zstyle ':completion:*' menu select

#======簡縮=======
alias na='nautilus'

# ==== autojump ====
# Do not want background jobs to be at a lower priority
unsetopt BG_NICE
# ==================

# ====== batcat ======
export BAT_THEME="TwoDark"
export BAT_STYLE="numbers,changes,grid"